# tests/pipeline/test_enriched_metadata_schema.py

import pytest
import json
import jsonschema
import time
from pathlib import Path

# 📘 Load schema from local JSON file
SCHEMA_PATH = Path("schemas/domain_schema.json")
with open(SCHEMA_PATH, "r") as schema_file:
    SCHEMA = json.load(schema_file)

# 📂 Reference output file generated by pipeline
OUTPUT_FILE = Path("output/test_enriched_metadata.json")

def load_payload():
    """Load pipeline output payload or skip if missing."""
    if not OUTPUT_FILE.exists():
        pytest.skip("Test output file not found. Run pipeline first.")
    with open(OUTPUT_FILE, "r") as f:
        return json.load(f)

def test_domain_definition_matches_schema():
    """Validate enriched metadata structure against domain schema."""
    data = load_payload()
    jsonschema.validate(instance=data, schema=SCHEMA)

def test_required_keys_are_present():
    """Check required fields in 'domain_definition' exist."""
    data = load_payload()
    dd = data.get("domain_definition")
    assert dd is not None
    required_keys = ["min_x", "max_x", "min_y", "max_y", "min_z", "max_z", "nx", "ny", "nz"]
    for key in required_keys:
        assert key in dd

def test_field_types_are_correct():
    """Ensure domain fields are properly typed."""
    data = load_payload()
    dd = data.get("domain_definition")
    assert isinstance(dd["nx"], int)
    assert isinstance(dd["ny"], int)
    assert isinstance(dd["nz"], int)
    for axis in ["min_x", "max_x", "min_y", "max_y", "min_z", "max_z"]:
        assert isinstance(dd[axis], float)

def test_metadata_fields_are_correct():
    """Verify metadata keys are present and float-valued."""
    data = load_payload()
    md = data.get("metadata")
    if md:
        for key in ["domain_size", "spacing_hint", "resolution_density"]:
            assert key in md
            assert isinstance(md[key], float)

def test_schema_rejects_extra_fields():
    """Ensure unexpected fields violate the schema."""
    sample = load_payload()
    sample["domain_definition"]["unexpected_key"] = "should_not_be_here"
    with pytest.raises(jsonschema.exceptions.ValidationError):
        jsonschema.validate(instance=sample, schema=SCHEMA)

def test_schema_validation_runtime():
    """Performance guard for schema validation."""
    data = load_payload()
    start = time.time()
    jsonschema.validate(instance=data, schema=SCHEMA)
    assert time.time() - start < 0.5  # seconds



