# .github/workflows/triggered.yml
name: Triggered Workflow

on:
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Echo trigger
        run: echo "Triggered by orchestrator"



