name: Triggered Workflow

on:
  workflow_dispatch:

jobs:
  log-and-delegate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log trigger event
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S'): the run was done by engineering_simulations_pipeline_autorun repository" >> trigger.txt

      - name: Commit and push trigger log
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"
          git add trigger.txt
          git commit -m "Log trigger from autorun orchestrator"
          git push

  call-simulation:
    uses: ./.github/workflows/fluid_simulation_pipeline.yml



